 ---
- hosts: linux
  remote_user: ansible-user
  become: yes
  gather_facts: no

  tasks:
  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
  - name: Enable service to start on boot
    service:
      name: httpd
      state: started

  - name: apache2 listen on port 8080
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
      notify:
        - restart apache2

  - name: apache2 virtualhost on port 8080
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
      notify:
        - restart apache2

  handlers:
  - name: restart apache2
      service: name=apache2 state=restarted

  - name: copy test.txt to linux server
    copy:
       src: /home/ansible/test.txt
       dest: /usr/local/apache2/htdocs/test.txt
       owner: www
       group: www
       mode: '0644'


